config/routes.rb
Rails.application.routes.draw do
  resources :infos

  root "infos#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :timeoutable
  devise :omniauthable, omniauth_providers: [:azure_oauth2]

  def self.from_omniauth(auth)
    user = find_by_email(auth.info.email)
    if user
        user.update(timeout: (auth.credentials.expires_at - Time.now.to_i)/60)
    else
      user = self.new
      user.email = auth.info.email
      user.name = auth.info.name
      user.timeout = (auth.credentials.expires_at - Time.now.to_i)/60
      user.save!
    end
    user
  end

  def timeout_in
    timeout.minutes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:name, :phone)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
require 'jwt'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def azure_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Azure AD') if is_navigational_format?

      # Retreive access token and decode it using JWT then print it to the console
      token = request.env["omniauth.auth"]["credentials"]["token"]
      decoded_token = JWT.decode token, nil, false
      # puts "*****************"
      # puts decoded_token
      # puts "*****************"

      url = URI('http://52.170.88.55/Discovery.Auth.API/api/Token/GetSecurityToken')
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = false
      request = Net::HTTP::Post.new(url, {'Content-Type' => 'application/json'})
      data = {"UserName":"Bassam@NitorSSO.onmicrosoft.com","Password":"NI@2018123","ClientId":"8e59734f-420f-47bf-b8e7-f9d8415b4e4d"}
      data_json = data.to_json
      request.body = data_json
      response = http.request(request)
      # puts "*****************"
      $role = response.body
      # puts "*****************"

    else
      session['devise.azure_oauth2_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end



  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create

  end

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    redirect_to "https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=#{root_url}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.haml
= form_for @info do |f|
  - if @info.errors.any?
    #error_explanation
      %h2= "#{pluralize(@info.errors.count, "error")} prohibited this info from being saved:"
      %ul
        - @info.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/infos/edit.html.haml
%h1 Editing info

= render 'form'

= link_to 'Show', @info
\|
= link_to 'Back', infos_path

app/views/infos/index.html.haml
%h1 Listing infos

%table
  %thead
    %tr
      %th Name
      %th Phone
      %th
      %th
      %th

  %tbody
    - @infos.each do |info|
      %tr
        %td= info.name
        %td= info.phone
        %td= link_to 'Show', info
        %td= link_to 'Edit', edit_info_path(info)
        %td= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Info', new_info_path

app/views/infos/new.html.haml
%h1 New info

= render 'form'

= link_to 'Back', infos_path

app/views/infos/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @info.name
%p
  %b Phone:
  = @info.phone

= link_to 'Edit', edit_info_path(@info)
\|
= link_to 'Back', infos_path

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title AzureAuth
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  - if current_user
    = current_user.name
    = $role
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign in with Azure account', user_azure_oauth2_omniauth_authorize_path
  = yield